### ISSUE TITLE
Learn pythonic stuff

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-slsh1o#12]
* [x] PEP8 (common conventions of writing and organizing code in the pythonic world)
* [x] PEP20 (Zen Of Python)
```python
import this
```
* [x] PEP257 (common conventions of writing docstrings)
* [x] [linters: flake8, pylint](https://joshpeak.net/posts/2019-06-18-Advanced-python-testing.html)
* [x] virtualenv
  * [x] pyenv (install one locally using pyenv-installer, enable pyenv-virtualenv as well) -> #11
* [x] zsh (install and enable this shell in your machine)
  * [x] install oh-my-zsh framework to configure nice and useful terminal environment -> #10

**Comment by slsh1o** [comment]
Have to say [this](https://joshpeak.net/posts/2019-06-18-Advanced-python-testing.html) article is pretty hard to read. Hard to say if I understand what I read about without real practice with testing for now. To be honest I am not sure about what I should do with info from the article. Does my goal is just to set flake8 to VS code and go through article to get overview of tools used to test python code? Or something else?

**Comment by webknjaz** [comment]
You may skip that article for now. It's just an example of deeper knowledge. In this task, you don't need to configure any linters, just learn that they exist and maybe look at a few usage examples. I added this link last minute because it was open in my browser and is a quite good overview of what's going on out there in the ecosystem but didn't really check if it's complicated.

I think that it's more important to know PEP 8 and PEP 257 now. When you'll start writing code, I'll ask you to follow those principles but right now I just want you to skim-through with the focus on trying to understand the motivation behind all those code style rules.
