### ISSUE TITLE
Configure integration of Heroku deployment with GitHub

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-slsh1o#20]
It's a follow-up for #19.

* [x] Accept invitation to [this organization](https://github.com/kpi-web-guild)
 * optionally make your membership public, so that there will be hat logo displayed on your profile page ^^
* [x] Choose [this repo](https://github.com/kpi-web-guild/django-girls-blog-slsh1o) in `Heroku Dashboard` on `Deploy` page
* [x] Make [`master` branch](https://github.com/kpi-web-guild/django-girls-blog-slsh1o/tree/master) be deployed on update once the tests pass

**Comment by slsh1o** [comment]
Sorry I am not sure where to accept the invitation:sweat_smile: (I can't see it).
Also I don't know how to choose this repo on Heroku Dashboard. Should it be pipeline or a new app? Is it my exercise to find out how?)

**Comment by webknjaz** [comment]
I haven't sent that invitation just yet so you can't see it or list the repo. I'll do it a bit later. Focus on delivering your current PR fist.

**Comment by slsh1o** [comment]
I've chosen this repo in Heroku to auto deploy after successful CI tests but it looks like it needs further configuration.

**Comment by webknjaz** [comment]
Yes, it does need extra work but it can be done later.
