### ISSUE TITLE
Learn Git

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-slsh1o#4]
![](https://i.pinimg.com/564x/25/73/14/257314878858202f4cf6b9ca37981cf0.jpg)

Please read&learn the following:

* [x] [ProGit 2](https://git-scm.com/book/en/v2) [:ukraine:](https://git-scm.com/book/uk/v2)
* [x] [Try Git](https://try.github.io/)
* [x] [Try Git Branching](http://learngitbranching.js.org/)
* [x] [Interactive diagram/cheatsheet about git](http://ndpsoftware.com/git-cheatsheet.html)
* [x] [You're using git wrong](https://web.archive.org/web/20181029051129/https://dpc.pw/blog/2017/08/youre-using-git-wrong/)
* [ ] [Learn git concepts, not commands](https://dev.to/unseenwizzard/learn-git-concepts-not-commands-4gjc)
* [ ] [The advantages of an email-driven git workflow](https://drewdevault.com/2018/07/02/Email-driven-git.html)
* [ ] [Git For Ages 4 And Up](https://youtu.be/1ffBJ4sVUb4)

Extras:
* [x] [A useful template for commit messages](http://codeinthehole.com/tips/a-useful-template-for-commit-messages/)
* [x] [Understanding the GitHub Flow](https://guides.github.com/introduction/flow/)
* [x] [Closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/)
* [ ] [email + git = <3](https://git-send-email.io/)

**Comment by slsh1o** [comment]
I have passed all exercises from [Try Git Branching](http://learngitbranching.js.org/). Also I have some previous git experience so along with this exercises and 'refreshments' from articles above I think I can move on to the next issues (which I hope you will add as soon as possible :smiley: ).
Regarding ProGit book I will use it as deep reference guide.

**Comment by webknjaz** [comment]
Just make sure you're familiar with sections 5, 7 and 8 of ProGit. These are quite useful and since it's a tool that you use often, you need to know how to do more complex things than just basics. The goal of this task is also to make you understand the distributed nature of Git.

Also, a few upcoming issues will guide you through writing good commit messages — they are as important as commit contents and help you maintain healthy Git history.
