### ISSUE TITLE
Create an empty commit on master (and push nothing else there!)

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-slsh1o#5]
```console
git commit --allow-empty -m 'Initial commit'
git push origin master
```

And report here after that.

**Comment by slsh1o** [comment]
Pushed empty init commit.
May I ask you to add some practice issues to make my hand 'dirty' with codding in addition to two other issues that I have? I would like to combine practice with theory:smile:.

**Comment by webknjaz** [comment]
Yes, sure. Just wanted to set up the repo properly for PRs with branch protection.

**Comment by webknjaz** [comment]
`master` is now protected. You cannot push there, all should be done via PRs with reviews.
